### ISSUE TITLE
Task List

### ISSUE THREAD

**Issue by anapecic** [anapecic/task-flow#1]
## Value Proposition

As a user
I want to browse a list of tasks,
so that I can see all my tasks in one place and stay organised.

## Description

![Image](https://github.com/user-attachments/assets/db974259-0670-4acd-8fb9-19cdf7f92eaa)

## Acceptance criteria
- The homepage displays a list of tasks.
- The tasks list is headlined with its purpose.
- Each task listing includes:
    - Task title
    - Task priority
    - Due date
- Tasks are ordered by due date, with tasks that are due soonest appearing at the top.
- Tasks due on the current date and those past their due date are visually highlighted.
- The list supports vertical scrolling to accommodate multiple entries.

## Tasks
- [x] Create the feature branch task-list.
- [x] Create state in order to store current tasks.
- [x] Display data according to state.
- [x] List items are displayed, each item includes priority-icon, date and title.
- [x] Items are ordered by due date, with tasks that are due soonest appearing at the top.

**Comment by natush-NO** [comment]
### Пропозиція Вартості

**Як користувач,**  
я хочу переглядати список завдань,  
щоб я міг бачити всі свої завдання в одному місці та залишатися організованим.

### Опис

**Зображення**

### Критерії Прийняття

1. Головна сторінка відображає список завдань.
2. Список завдань має заголовок, що відображає його призначення.
3. Кожен елемент списку завдань включає:
   - Заголовок завдання
   - Пріоритет завдання
   - Дату виконання
4. Завдання впорядковані за датою виконання, при цьому завдання, термін яких наближається, відображаються зверху.
5. Завдання, термін виконання яких на сьогоднішній день або які прострочені, візуально виділені.
6. Список підтримує вертикальне прокручування для відображення кількох записів.

### Завдання

1. Створіть гілку функцій `task-list`.
2. Створіть стан для зберігання поточних завдань.
3. Відображайте дані відповідно до стану.
4. Елементи списку відображаються, кожен елемент включає значок пріоритету, дату та заголовок.
5. Елементи впорядковані за датою виконання, при цьому завдання, термін яких наближається, відображаються зверху.
