### ISSUE TITLE
Design

### ISSUE THREAD

**Issue by anapecic** [anapecic/task-flow#11]
## Value proposition

As a user
I want to see a nicely designed page across the app
In order to feel connected to the brand.

## Description
![Image](https://github.com/user-attachments/assets/3b48d71f-439b-465d-be06-e19b2b7a8c46)

red - #f90001
yellow - #fde406
green - #52fd00
background grey - #f3f1fb
darker grey - #d3d3d3
shadow grey - #bab8be
blue - #3672a9

## Acceptance criteria
- [ ] All pages are consistently styled according to the Wireframe.
- [ ] All elements are styled according to our color palette.
- [ ] The design is responsive and works for mobile & desktop users.
- [ ] The design is accessible. 

## Tasks
- [ ] We use styled components and do not use other forms of importing CSS.
- [ ] We try to stick to one unit as much as possible, preferring rem for fonts, paddings & margins while using pixel for fixed sizes of elements if explicitly needed.
- [ ] The styling uses responsive methods like flexbox and grid instead of hardcoded styles that are open to issues in responsiveness.

**Comment by Inelukas** [comment]
Looks fine! Regarding units: I would suggest using px for paddings & margins to prevent scaling issues for users that use a modified standard font-size for their browsers -> [Josh Comeau wrote a great article about this](https://www.joshwcomeau.com/css/surprising-truth-about-pixels-and-accessibility/)

**Comment by natush-NO** [comment]
**Ціннісна пропозиція**  
**Як користувач**  
Я хочу бачити добре оформлену сторінку по всьому додатку  
Щоб відчувати зв'язок з брендом.

**Опис**  
Зображення

- червоний - #f90001
- жовтий - #fde406
- зелений - #52fd00
- фон сірий - #f3f1fb
- темніший сірий - #d3d3d3
- сірий для тіні - #bab8be
- синій - #3672a9

**Критерії прийняття**

- Усі сторінки мають бути консистентно оформлені відповідно до Wireframe.
- Усі елементи мають бути стилізовані відповідно до нашої кольорової палітри.
- Дизайн має бути адаптивним і працювати як для мобільних, так і для десктопних користувачів.
- Дизайн має бути доступним.

**Завдання**

- Ми використовуємо styled-components і не використовуємо інші форми імпорту CSS.
- Ми намагаємося дотримуватись однієї одиниці виміру, віддаючи перевагу rem для шрифтів, відступів і маргінів, а також використовуючи пікселі для фіксованих розмірів елементів, якщо це явно необхідно.
- Стилізація використовує адаптивні методи, такі як flexbox і grid, замість жорстко закодованих стилів, які можуть спричиняти проблеми з адаптивністю.
