### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by anapecic** [anapecic/task-flow#17]
## Value proposition

As a user,
I want to change to Dark mode,
so I can easier read my Tasks in the dark.

## Description

![Image](https://github.com/user-attachments/assets/d9f3651c-25f2-453e-8383-622c922e10ce)
![Image](https://github.com/user-attachments/assets/729e1197-0d34-41ba-824c-5b4ac43626cc)

## Acceptance criteria
- [ ] Button to change between bright/dark-mode.
- [ ] Page and content (fonts, icons, etc.) change color by clicking.
- [ ] Button changes (sun->bright, moon->dark).
- [ ] If there is an element without dark-mode styling, keep bright-mode styling instead.

## Tasks
- [ ] Create feature branch "dark-mode"
- [ ] Create and design dark-mode toggle button.
- [ ] Add event listeners to the button to handle the switch between bright/dark-mode.
- [ ] Define and implement dark-mode styles across the page (background colors, text colors, icons, etc.).
- [ ] Handle fallback for elements without dark-mode styling, so they will keep their bright-mode styles instead.

**Comment by natush-NO** [comment]
**Ціннісна пропозиція**  
**Як користувач,**  
Я хочу перемикатися на темний режим,  
щоб мені було легше читати завдання в темряві.

**Опис**  
Зображення  
Зображення

**Критерії прийняття**

- Кнопка для перемикання між світлим і темним режимами.
- Сторінка та контент (шрифти, іконки тощо) змінюють колір при натисканні.
- Кнопка змінює іконки (сонце -> світлий режим, місяць -> темний режим).
- Якщо є елемент без стилізації для темного режиму, зберігайте стилізацію для світлого режиму замість цього.

**Завдання**

- Створити гілку для функції "темний режим".
- Створити та спроектувати кнопку перемикання темного режиму.
- Додати обробники подій до кнопки для керування перемиканням між світлим і темним режимами.
- Визначити та реалізувати стилі темного режиму по всій сторінці (фонові кольори, кольори тексту, іконки тощо).
- Обробити випадки для елементів без стилізації темного режиму, щоб вони зберігали стилі світлого режиму замість цього.
